[build]
  command = "npm run build"
  publish = "client/dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"  # Specify the bundler
  included_files = [
    "netlify/functions/**/*"
  ]
